# Generated by Django 2.2.3 on 2019-07-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_word', models.CharField(max_length=200, verbose_name='Матерное слово')),
            ],
            options={
                'verbose_name': 'Матерное слово',
                'verbose_name_plural': 'Матерные слова',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('fathername', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='ExceptionWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_word', models.CharField(max_length=200, verbose_name='Слова-исключения')),
            ],
            options={
                'verbose_name': 'Слово-исключение',
                'verbose_name_plural': 'Слова-исключения',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность:')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('first_review', models.TextField(verbose_name='Исходный отзыв')),
                ('changed_review', models.TextField(verbose_name='Изменённый отзыв')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainPage.Doctor', verbose_name='Врач')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='MainPage.Specialty', verbose_name='Специальности'),
        ),
    ]
